// Karma configuration
// Generated on Thu Oct 13 2016 16:02:06 GMT-0400 (Eastern Daylight Time)
module.exports = function(config) {
    config.set({
        basePath : '..',
        frameworks: ["jasmine", "karma-typescript"],
        files: [
            "src/ICad/Event/EventEmitter.ts",
            "src/ICad/View/AbstractView.ts",
            "src/ICad/View/DOM/DOM.ts",
            "src/ICad/View/DOM/DOMEmitter.ts",
            "src/ICad/Controller/AbstractCtrl.ts",
            "src/ICad/View/Text/TextInterface.ts",

            'src/ICad/Action/Action.ts',
            'src/ICad/Action/ActionAppWorkflow.ts',
            'src/ICad/Action/Call.ts',
            'src/ICad/Action/OpenHome.ts',
            'src/ICad/Action/OpenLog.ts',
            'src/ICad/Action/OpenSample.ts',
            'src/ICad/Application/AbstractApplication.ts',
            'src/ICad/Application/Browser.ts',
            'src/ICad/Application/Cordova.ts',
            'src/ICad/Controller/AbstractCompositeCtrl.ts',
            'src/ICad/Controller/Factory.ts',
            'src/ICad/Controller/Container/AbstractTabularCtrl.ts',
            'src/ICad/Controller/Container/FrameCtrl.ts',
            'src/ICad/Controller/Container/SideBarCtrl.ts',
            'src/ICad/Controller/Misc/HomeCtrl.ts',
            'src/ICad/Controller/Model/AbstractModelCtrl.ts',
            'src/ICad/Controller/Model/AbstractModelDetailCtrl.ts',
            'src/ICad/Controller/Model/AbstractModelListCtrl.ts',
            'src/ICad/Controller/Model/StorageExplorerCtrl.ts',
            'src/ICad/Controller/Model/Well/Borehole/BoreholeColumnCtrl.ts',
            'src/ICad/Controller/Model/Well/Borehole/BoreholeColumnDataCtrl.ts',
            'src/ICad/Controller/Model/Well/Borehole/BoreholeColumnHeaderCtrl.ts',
            'src/ICad/Controller/Model/Well/Log/LogColumnDataCtrl.ts',
            'src/ICad/Controller/Model/Well/Log/LogColumnHeaderCtrl.ts',
            'src/ICad/Controller/Model/Well/Log/LogDataCtrl.ts',
            'src/ICad/Controller/Model/Well/Project/ProjectFrameCtrl.ts',
            'src/ICad/Controller/Model/Well/Trace/AbstractTracesRendererCtrl.ts',
            'src/ICad/Controller/Model/Well/Trace/TracesRendererBitmapCtrl.ts',
            'src/ICad/Event/Event.ts',
            'src/ICad/Event/Registration.ts',
            'src/ICad/Math/Matrix.ts',
            'src/ICad/Math/Color/Color.ts',
            'src/ICad/Math/Geometry/Point.ts',
            'src/ICad/Math/Geometry/Rectangle.ts',
            'src/ICad/Model/AbstractModel.ts',
            'src/ICad/Model/Directory.ts',
            'src/ICad/Model/Well/Borehole.ts',
            'src/ICad/Model/Well/Log.ts',
            'src/ICad/Model/Well/Project.ts',
            'src/ICad/Model/Well/Trace.ts',
            'src/ICad/Storage/AbstractStorage.ts',
            'src/ICad/Storage/Factory.ts',
            'src/ICad/Storage/FakeStorage.ts',
            'src/ICad/Storage/Query.ts',
            'src/ICad/Util/Random.ts',
            'src/ICad/Util/Unicity.ts',
            'src/ICad/View/AbstractFactory.ts',
            'src/ICad/View/Button/ButtonInterface.ts',
            'src/ICad/View/Button/ButtonDOM.ts',
            'src/ICad/View/DOM/Body.ts',
            'src/ICad/View/DOM/Canvas.ts',
            'src/ICad/View/DOM/CanvasWebGL.ts',
            'src/ICad/View/DOM/Factory.ts',
            'src/ICad/View/Image/ImageInterface.ts',
            'src/ICad/View/Image/Bitmap/BitmapInterface.ts',
            'src/ICad/View/Image/Bitmap/BitmapCanvasWebGL.ts',
            'src/ICad/View/Text/ParagraphInterface.ts',
            'src/ICad/View/Text/TitleInterface.ts',
            'src/ICad/View/Text/ParagraphDOM.ts',
            'src/ICad/View/Text/TitleDOM.ts',
            'tests/karma/**/*'
        ],
        preprocessors: {
            "**/*.ts": "karma-typescript"
        },
        karmaTypescriptConfig: {
            compilerOptions: {
                "target": "es6",
            }
        },
        reporters: ["progress", "karma-typescript"],
        browsers: ["Chrome"]
    });
};